project:
  type: website

website:
  title: "2025303110096"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

project:
  type: website
  output-dir: docs  # 将输出目录指定为 docs，GitHub Pages 默认识别此目录


